### ISSUE TITLE
filter queries not working

### ISSUE THREAD

**Issue by jgravois** [jgravois/koop-walmart#2]
i remember @dmfenton saying that this isn't supported when features don't have an OBJECTID, but they're present here. any other suggestions?

https://h8w2a8ip0c.execute-api.us-east-1.amazonaws.com/latest/walmart/FeatureServer/0/query?where=status=Closed

```json
{ "features": [] }
```
https://h8w2a8ip0c.execute-api.us-east-1.amazonaws.com/latest/walmart/FeatureServer/0/query?where=city=KANSAS%20CITY

```json
{
  "error": "Parse error on line 1:\n...es->`city` = KANSAS CITY\n-----------------------^\nExpecting 'EOF', 'WITH', 'RPAR', 'IN', 'LIKE', 'ARROW', 'DOT', 'ORDER', 'CARET', 'EQ', 'SLASH', 'EXCLAMATION', 'MODULO', 'GT', 'LT', 'GTGT', 'LTLT', 'NOT', 'UNION', 'INTERSECT', 'EXCEPT', 'AND', 'OR', 'PLUS', 'STAR', 'GROUP', 'LIMIT', 'OFFSET', 'END', 'ELSE', 'REGEXP', 'TILDA', 'GLOB', 'NOT_LIKE', 'BARBAR', 'MINUS', 'AMPERSAND', 'BAR', 'GE', 'LE', 'EQEQ', 'EQEQEQ', 'NE', 'NEEQEQ', 'NEEQEQEQ', 'BETWEEN', 'NOT_BETWEEN', 'IS', 'DOUBLECOLON', 'GO', 'SEMICOLON', got 'LITERAL'"
}
```

**Comment by dmfenton** [comment]
https://h8w2a8ip0c.execute-api.us-east-1.amazonaws.com/latest/walmart/FeatureServer/0/query?where=city=%22KANSAS%20CITY%22

**Comment by jgravois** [comment]
headslap
